# Generated by Django 3.1.7 on 2021-03-27 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='taskTable',
        ),
    ]
